name: Dev Build

on:
  push:
    branches: [ "dev" ]

jobs:
  call_build:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable_build.yml
    with:
      is-release-build: false
      release-version-type: 'beta'
      publish-artifacts: true
    secrets: inherit